on:
    pull_request:
    merge_group:

name: Audit Actions

permissions:
    contents: read

jobs:
    ensure-pinned-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Ensure SHA pinned actions
              uses: zgosalvez/github-actions-ensure-sha-pinned-actions@cc9ffdc62fadb9f83b46dd0979d9ad50408cc6a6 # v5.0.2
              with:
                  allowlist: |
                      actions/
                      github/
                      PostHog/
                      posthog/
