on:
    push:
        branches:
            - main
    pull_request:
    merge_group:

name: Security

permissions:
    contents: read

env:
    SEMGREP_ENABLE_VERSION_CHECK: 'false'

jobs:
    # scans GitHub Actions and other repo-wide config
    semgrep-local:
        runs-on: ubuntu-latest
        container:
            image: semgrep/semgrep

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            # exclude all directories already scanned by other jobs
            - name: Run Semgrep
              run: |
                  semgrep \
                    --config "p/owasp-top-ten" \
                    --config "p/security-audit" \
                    --config "p/trailofbits" \
                    --config "p/github-actions" \
                    --error \
                    --metrics=off \
                    --verbose \
                    .
